spring:
  application:
    name: petshop-app
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petshop-database
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

server:
  port: 8080

jwt:
  secret: secret

graphiql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    endpoint:
      graphql: /graphql
    pageTitle: GraphiQL
    props:
      variables:
        editorTheme: "solarized light"

